# Generated by Django 5.0.1 on 2024-01-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_position_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='./registration/static/profile_images', verbose_name='Фото профиля'),
        ),
    ]
