# Generated by Django 4.2.9 on 2024-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_client_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Пользователь'),
        ),
    ]
