# Generated by Django 4.2.9 on 2024-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_route_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пользователь'),
        ),
    ]
