# Generated by Django 4.2.9 on 2024-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phone_alter_clientobjectsprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientobjectsprofile',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='clientobjectsprofile',
            name='lat',
            field=models.CharField(default=None, max_length=20, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='clientobjectsprofile',
            name='lon',
            field=models.CharField(default=None, max_length=20, verbose_name='Долгота'),
        ),
    ]
