# Generated by Django 4.2.9 on 2024-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clientobjectsprofile_geolocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clientobjectsprofile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
